//! Konveyor output format types.
//!
//! Mirrors the analyzer-lsp output YAML/JSON format so that the standalone CLI
//! produces output consumable by Konveyor Hub, the fix command, or any other
//! Konveyor-compatible tooling.

use crate::incident::Incident;
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

/// Top-level output: a list of RuleSets.
pub type AnalysisOutput = Vec<RuleSet>;

/// A set of rules and their matched violations.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RuleSet {
    /// Ruleset name.
    pub name: String,

    /// Ruleset description.
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub description: String,

    /// Tags generated by matched tagging rules.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub tags: Vec<String>,

    /// Map of rule ID -> Violation for matched rules.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub violations: BTreeMap<String, Violation>,

    /// Map of rule ID -> Violation for informational rules.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub insights: BTreeMap<String, Violation>,

    /// Map of rule ID -> error string for failed evaluations.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub errors: BTreeMap<String, String>,

    /// Rule IDs evaluated but not matched.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub unmatched: Vec<String>,

    /// Rule IDs skipped.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub skipped: Vec<String>,
}

/// A violation produced when a rule matches.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Violation {
    /// Description of the violation (from the rule).
    pub description: String,

    /// Severity category.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub category: Option<Category>,

    /// Labels from the rule.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub labels: Vec<String>,

    /// Individual match instances.
    #[serde(default)]
    pub incidents: Vec<ViolationIncident>,

    /// Hyperlinks for docs/fixes.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub links: Vec<Link>,

    /// Story points per incident.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub effort: Option<i32>,
}

/// An incident in the Konveyor output format.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ViolationIncident {
    /// File URI.
    pub uri: String,

    /// Human-readable message about the incident.
    pub message: String,

    /// Surrounding source code.
    #[serde(rename = "codeSnip", skip_serializing_if = "Option::is_none")]
    pub code_snip: Option<String>,

    /// Line number.
    #[serde(rename = "lineNumber", skip_serializing_if = "Option::is_none")]
    pub line_number: Option<u32>,

    /// Custom variables.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub variables: BTreeMap<String, serde_json::Value>,
}

/// Severity category for a violation.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "lowercase")]
pub enum Category {
    Mandatory,
    Optional,
    Potential,
}

/// A hyperlink.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Link {
    pub url: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
}

impl From<&Incident> for ViolationIncident {
    fn from(incident: &Incident) -> Self {
        ViolationIncident {
            uri: incident.file_uri.clone(),
            message: String::new(), // filled in by the engine from the rule
            code_snip: incident.code_snip.clone(),
            line_number: Some(incident.line_number),
            variables: incident.variables.clone(),
        }
    }
}
